-- MySQL Script generated by MySQL Workbench
-- Mon Nov 16 07:51:40 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banco
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `banco` ;

-- -----------------------------------------------------
-- Schema banco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco` DEFAULT CHARACTER SET utf8 ;
USE `banco` ;

-- -----------------------------------------------------
-- Table `banco`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banco`.`cliente` ;

CREATE TABLE IF NOT EXISTS `banco`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(75) NOT NULL,
  `apellido` VARCHAR(75) NOT NULL,
  `telefono` VARCHAR(8) NOT NULL,
  `correo` VARCHAR(85) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`tipo_transaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banco`.`tipo_transaccion` ;

CREATE TABLE IF NOT EXISTS `banco`.`tipo_transaccion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(65) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `descripcion_UNIQUE` (`descripcion` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banco`.`cuenta` ;

CREATE TABLE IF NOT EXISTS `banco`.`cuenta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `moneda` VARCHAR(3) NOT NULL,
  `fondo` DECIMAL(8,2) NOT NULL,
  `cliente_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cuenta_cliente_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_cuenta_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `banco`.`cliente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`transaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banco`.`transaccion` ;

CREATE TABLE IF NOT EXISTS `banco`.`transaccion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cuenta_id` INT NOT NULL,
  `tipo_transaccion_id` INT NOT NULL,
  `monto` DECIMAL(8,2) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transaccion_cuenta1_idx` (`cuenta_id` ASC),
  INDEX `fk_transaccion_tipo_transaccion1_idx` (`tipo_transaccion_id` ASC),
  CONSTRAINT `fk_transaccion_cuenta`
    FOREIGN KEY (`cuenta_id`)
    REFERENCES `banco`.`cuenta` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_transaccion_tipo_transaccion`
    FOREIGN KEY (`tipo_transaccion_id`)
    REFERENCES `banco`.`tipo_transaccion` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
